name: Git Action Workflow

on:
  push:
    branches:
      - main

jobs:
  read_hello_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read and Print hello.txt
        run: |
          echo "Reading hello.txt..."
          cat hello.txt || echo "hello.txt not found"


